package luxmcp.lux;

import io.modelcontextprotocol.json.McpJsonDefaults;
import io.modelcontextprotocol.json.TypeRef;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

/**
 * The register dictionary: every known parameter / calculation / visibility with its datatype.
 * <p>
 * Backed by {@code /luxtronik/registers.json}, generated by {@code tools/gen_registers.py} from
 * python-luxtronik. Lookups by name are case-insensitive; if several definitions exist for the
 * same index the last one wins (same rule as upstream).
 */
public final class Registers {

    private final Map<String, DataType> datatypes = new HashMap<>();
    private final Map<RegisterKind, List<RegisterDef>> defs = new EnumMap<>(RegisterKind.class);
    private final Map<RegisterKind, Map<String, RegisterDef>> byName = new EnumMap<>(RegisterKind.class);
    private final Map<RegisterKind, Map<Integer, RegisterDef>> byIndex = new EnumMap<>(RegisterKind.class);
    private final String sourceInfo;

    /** Load the register table bundled in the jar. */
    public static Registers load() {
        try (InputStream in = Registers.class.getResourceAsStream("/luxtronik/registers.json")) {
            if (in == null) {
                throw new IllegalStateException("registers.json missing from classpath - run tools/gen_registers.py");
            }
            return new Registers(in.readAllBytes());
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    @SuppressWarnings("unchecked")
    public Registers(byte[] json) throws IOException {
        Map<String, Object> root = McpJsonDefaults.getMapper().readValue(json, new TypeRef<Map<String, Object>>() {
        });
        Map<String, Object> types = (Map<String, Object>) root.get("datatypes");
        for (Map.Entry<String, Object> e : types.entrySet()) {
            datatypes.put(e.getKey(), DataType.fromJson(e.getKey(), (Map<String, Object>) e.getValue()));
        }
        for (RegisterKind kind : RegisterKind.values()) {
            List<RegisterDef> list = new ArrayList<>();
            Map<String, RegisterDef> names = new HashMap<>();
            Map<Integer, RegisterDef> index = new HashMap<>();
            List<Map<String, Object>> raw = (List<Map<String, Object>>) root.get(kind.jsonKey);
            if (raw != null) {
                for (Map<String, Object> m : raw) {
                    RegisterDef d = toDef(kind, m);
                    list.add(d);
                    for (String n : d.names()) {
                        names.put(n.toLowerCase(Locale.ROOT), d);
                    }
                    index.put(d.index(), d);
                }
            }
            list.sort((a, b) -> Integer.compare(a.index(), b.index()));
            defs.put(kind, Collections.unmodifiableList(list));
            byName.put(kind, names);
            byIndex.put(kind, index);
        }
        try (InputStream notes = Registers.class.getResourceAsStream("/luxtronik/register_notes.tsv")) {
            if (notes != null) {
                applyNotes(new String(notes.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8));
            }
        }
        Map<String, Object> src = (Map<String, Object>) root.get("source");
        sourceInfo = src == null ? "unknown" : "python-luxtronik " + src.get("package_version")
                + (src.get("git_commit") != null ? " @" + String.valueOf(src.get("git_commit")).substring(0, 10) : "")
                + " (generated " + src.get("generated") + ")";
    }

    @SuppressWarnings("unchecked")
    private RegisterDef toDef(RegisterKind kind, Map<String, Object> m) {
        String typeName = String.valueOf(m.get("type"));
        DataType type = datatypes.get(typeName);
        if (type == null) {
            throw new IllegalStateException("registers.json references unknown datatype " + typeName);
        }
        Object namesObj = m.get("names");
        List<String> names = namesObj instanceof List ? new ArrayList<>((List<String>) namesObj) : List.of(String.valueOf(namesObj));
        return new RegisterDef(kind,
                ((Number) m.get("index")).intValue(),
                m.get("count") == null ? 1 : ((Number) m.get("count")).intValue(),
                Collections.unmodifiableList(names),
                type,
                Boolean.TRUE.equals(m.get("writeable")),
                str(m.get("datatype")), str(m.get("unit")), str(m.get("description")),
                str(m.get("since")), str(m.get("until")),
                m.get("successor") == null ? null : String.valueOf(m.get("successor")));
    }

    private static String str(Object o) {
        return o == null ? "" : String.valueOf(o);
    }

    /**
     * Merge curated notes ({@code name<TAB>note} per line, {@code #} comments) into the register
     * descriptions. Upstream descriptions are empty for nearly all registers.
     */
    int applyNotes(String tsv) {
        int applied = 0;
        for (String line : tsv.split("\\R")) {
            if (line.isBlank() || line.startsWith("#")) {
                continue;
            }
            int tab = line.indexOf('\t');
            if (tab <= 0) {
                continue;
            }
            String name = line.substring(0, tab).trim();
            String note = line.substring(tab + 1).trim();
            for (RegisterKind kind : RegisterKind.values()) {
                RegisterDef old = byName.get(kind).get(name.toLowerCase(Locale.ROOT));
                if (old == null) {
                    continue;
                }
                String desc = old.description().isEmpty() ? note : old.description() + " " + note;
                RegisterDef nu = new RegisterDef(old.kind(), old.index(), old.count(), old.names(), old.type(),
                        old.writeable(), old.datatype(), old.unit(), desc, old.since(), old.until(), old.successor());
                List<RegisterDef> list = new ArrayList<>(defs.get(kind));
                list.replaceAll(d -> d == old ? nu : d);
                defs.put(kind, Collections.unmodifiableList(list));
                for (String n : nu.names()) {
                    byName.get(kind).put(n.toLowerCase(Locale.ROOT), nu);
                }
                if (byIndex.get(kind).get(nu.index()) == old) {
                    byIndex.get(kind).put(nu.index(), nu);
                }
                applied++;
                break;
            }
        }
        return applied;
    }

    public String sourceInfo() {
        return sourceInfo;
    }

    public DataType datatype(String name) {
        return datatypes.get(name);
    }

    /** All definitions of a kind, sorted by index (several entries may share an index). */
    public List<RegisterDef> all(RegisterKind kind) {
        return defs.get(kind);
    }

    /** Find by name (case-insensitive) or by numeric index (as string) within one kind. */
    public Optional<RegisterDef> find(RegisterKind kind, String nameOrIndex) {
        if (nameOrIndex == null) {
            return Optional.empty();
        }
        String key = nameOrIndex.trim();
        RegisterDef d = byName.get(kind).get(key.toLowerCase(Locale.ROOT));
        if (d == null && key.matches("-?\\d+")) {
            d = byIndex.get(kind).get(Integer.parseInt(key));
        }
        return Optional.ofNullable(d);
    }

    public Optional<RegisterDef> find(RegisterKind kind, int index) {
        return Optional.ofNullable(byIndex.get(kind).get(index));
    }

    /**
     * Find by name across all kinds (parameters first, then calculations, then visibilities).
     * Numeric indices are ambiguous across kinds and are therefore not accepted here.
     */
    public Optional<RegisterDef> find(String name) {
        if (name == null) {
            return Optional.empty();
        }
        for (RegisterKind k : RegisterKind.values()) {
            RegisterDef d = byName.get(k).get(name.trim().toLowerCase(Locale.ROOT));
            if (d != null) {
                return Optional.of(d);
            }
        }
        return Optional.empty();
    }

    /**
     * Case-insensitive search. Every whitespace separated token of {@code query} must occur in the
     * register name, datatype name, unit or description.
     */
    public List<RegisterDef> search(String query, RegisterKind kind, boolean includeUnknown, boolean writeableOnly) {
        String[] tokens = query == null ? new String[0] : query.trim().toLowerCase(Locale.ROOT).split("\\s+");
        List<RegisterDef> result = new ArrayList<>();
        for (RegisterKind k : RegisterKind.values()) {
            if (kind != null && kind != k) {
                continue;
            }
            for (RegisterDef d : defs.get(k)) {
                if (!includeUnknown && d.isUnknown()) {
                    continue;
                }
                if (writeableOnly && !d.writeable()) {
                    continue;
                }
                String hay = (String.join(" ", d.names()) + " " + d.type().name() + " " + d.unit() + " "
                        + d.description()).toLowerCase(Locale.ROOT);
                boolean ok = true;
                for (String t : tokens) {
                    if (!t.isEmpty() && !hay.contains(t)) {
                        ok = false;
                        break;
                    }
                }
                if (ok) {
                    result.add(d);
                }
            }
        }
        return result;
    }
}
